# Generated by Django 5.2.1 on 2025-07-11 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("courses", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="systemsettings",
            options={
                "verbose_name": "System Customization",
                "verbose_name_plural": "System Customizations",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="staff_courses",
            field=models.ManyToManyField(
                blank=True, related_name="staff_members", to="courses.course"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="student_courses",
            field=models.ManyToManyField(
                blank="True", related_name="students", to="courses.course"
            ),
        ),
        migrations.CreateModel(
            name="StudentDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="student_documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
