# Generated by Django 5.2.1 on 2025-07-11 22:07

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_client_feature_testimonial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="content",
        ),
        migrations.AddField(
            model_name="homepage",
            name="sections",
            field=wagtail.fields.StreamField(
                [("feature", 3), ("testimonial", 6), ("image_gallery", 7)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Bootstrap Icon class, e.g., bi-person",
                            "required": True,
                        },
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    2: ("wagtail.blocks.TextBlock", (), {"required": True}),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("icon", 0), ("title", 1), ("text", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.TextBlock", (), {}),
                    5: ("wagtail.blocks.CharBlock", (), {}),
                    6: (
                        "wagtail.blocks.StructBlock",
                        [[("quote", 4), ("author", 5)]],
                        {},
                    ),
                    7: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                },
            ),
        ),
        migrations.DeleteModel(
            name="AboutPage",
        ),
    ]
