# Generated by Django 5.2.1 on 2025-07-12 13:45

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remove_homepage_content_homepage_sections_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpage",
            name="page_ptr",
        ),
        migrations.AddField(
            model_name="homepage",
            name="button_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="button_text",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_image",
            field=wagtail.fields.StreamField(
                [("image", 0)],
                blank=True,
                block_lookup={0: ("wagtail.images.blocks.ImageChooserBlock", (), {})},
            ),
        ),
        migrations.DeleteModel(
            name="BlogIndexPage",
        ),
        migrations.DeleteModel(
            name="BlogPage",
        ),
    ]
